import { createSignal, For, onCleanup, Show } from "solid-js";
import { mnemonicToAccount } from "viem/accounts";
import { formatEther, parseEther, type Address } from "viem";
import { clearEphemeralBurner, createEphemeralBurner, readSepoliaBalance, SEPOLIA_FAUCET } from "./burner";
import { newMnemonic, validMnemonic, encryptMnemonic, decryptMnemonic, type EncryptedVault } from "@bunker/vault";
import { parseEnvelope, sealEnvelope, serializeEnvelope } from "@bunker/offline";
import { ZERO_ADDRESS } from "@bunker/core";

type View="welcome"|"burner"|"create"|"confirm"|"vault"|"home"|"send"|"offline"|"settings";
let secretMnemonic:string|undefined;
const wipe=()=>{secretMnemonic=undefined};
const short=(v:string)=>`${v.slice(0,8)}…${v.slice(-6)}`;
function download(name:string,data:string){const url=URL.createObjectURL(new Blob([data],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
const Icon=(p:{name:"shield"|"route"|"file"|"gear"})=><svg viewBox="0 0 24 24" aria-hidden="true"><path d={p.name==="shield"?"M12 2 20 5v6c0 5-3.4 9.4-8 11-4.6-1.6-8-6-8-11V5l8-3Zm0 3.2L7 7v4c0 3.5 2 6.6 5 8 3-1.4 5-4.5 5-8V7l-5-1.8Z":p.name==="route"?"M6 3a3 3 0 1 0 0 6 3 3 0 0 0 0-6Zm12 12a3 3 0 1 0 0 6 3 3 0 0 0 0-6ZM6 7v5a5 5 0 0 0 5 5h4v-2h-4a3 3 0 0 1-3-3V7H6Z":p.name==="file"?"M5 2h9l5 5v15H5V2Zm2 2v16h10V9h-5V4H7Zm7 .8V7h2.2L14 4.8Z":"M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0 2a2 2 0 1 1 0 4 2 2 0 0 1 0-4Zm9 3v-2l-2.1-.7a7 7 0 0 0-.7-1.7l1-2-1.4-1.4-2 1a7 7 0 0 0-1.7-.7L13 3h-2l-.7 2.1a7 7 0 0 0-1.7.7l-2-1-1.4 1.4 1 2a7 7 0 0 0-.7 1.7L3 11v2l2.1.7c.2.6.4 1.2.7 1.7l-1 2 1.4 1.4 2-1c.5.3 1.1.5 1.7.7L11 21h2l.7-2.1c.6-.2 1.2-.4 1.7-.7l2 1 1.4-1.4-1-2c.3-.5.5-1.1.7-1.7L21 13Z"}/></svg>;
export default function App(){
 const [view,setView]=createSignal<View>("welcome"),[theme,setTheme]=createSignal<"dark"|"light">((localStorage.getItem("bunker-theme") as "dark"|"light")||"dark"),[message,setMessage]=createSignal(""),[owner,setOwner]=createSignal<Address|undefined>(),[burnerAddress,setBurnerAddress]=createSignal<Address>(),[burnerBalance,setBurnerBalance]=createSignal<string>("Waiting for faucet"),[burnerCopy,setBurnerCopy]=createSignal("Copying address…"),[remaining]=createSignal(19),[backupConfirmed,setBackupConfirmed]=createSignal(false);
 let phraseEl!:HTMLOListElement; let confirmInputs:HTMLInputElement[]=[]; let password!:HTMLInputElement; let restore!:HTMLTextAreaElement; let offlineInput!:HTMLTextAreaElement;
 const connected=()=>Boolean(owner()||burnerAddress());
 const go=(v:View)=>{setMessage("");setView(v)};
 const loadWallet=()=>go(localStorage.getItem("bunker-vault")?"home":"confirm");
 const exitWallet=()=>{wipe();clearEphemeralBurner();setOwner();setBurnerAddress();go("welcome")};
 const derive=(m:string)=>{const a=mnemonicToAccount(m,{path:"m/44'/60'/7331'/0/0"});setOwner(a.address)};
 const create=()=>{secretMnemonic=newMnemonic();queueMicrotask(()=>{phraseEl.innerHTML=secretMnemonic!.split(" ").map((w,i)=>`<li><span>${i+1}</span>${w}</li>`).join("")});go("create")};
 const refreshBurner=async()=>{const address=burnerAddress();if(!address)return;setBurnerBalance("Checking Sepolia…");try{setBurnerBalance(`${Number(formatEther(await readSepoliaBalance(address))).toFixed(4)} Sepolia ETH`)}catch{setBurnerBalance("Balance unavailable — try again")}};
 const openFaucet=()=>{const address=burnerAddress()??createEphemeralBurner();setBurnerAddress(address);setBurnerBalance("Waiting for faucet");setBurnerCopy("Copying address…");const popup=window.open(SEPOLIA_FAUCET,"_blank","noopener,noreferrer");go("burner");if(!popup)setMessage("The faucet popup was blocked. Allow popups, then use Open Sepolia faucet.");if(navigator.clipboard)void navigator.clipboard.writeText(address).then(()=>setBurnerCopy("Copied to clipboard")).catch(()=>setBurnerCopy("Copy unavailable — select the address"));else setBurnerCopy("Copy unavailable — select the address")};
 onCleanup(clearEphemeralBurner);
 const confirmBackup=()=>{const words=secretMnemonic?.split(" ");if(!words)return; if(confirmInputs.map(x=>x.value.trim().toLowerCase()).join("|")!==[2,8,17].map(i=>words[i]).join("|")){setMessage("Those words do not match. Check the recovery phrase and try again.");return}go("vault")};
 const finishVault=async(persist:boolean)=>{if(!secretMnemonic)return;if(persist){if(password.value.length<12){setMessage("Use a password of at least 12 characters.");return}try{const vault=await encryptMnemonic(secretMnemonic,password.value,{chainId:31337,derivation:"m/44'/60'/7331'/0/index",sequenceVersion:1});localStorage.setItem("bunker-vault",JSON.stringify(vault));derive(secretMnemonic);wipe();go("home")}catch(e){setMessage(e instanceof Error?e.message:"Vault creation failed.")}}else{derive(secretMnemonic);go("home")}};
 const restorePhrase=()=>{const m=restore.value.trim();if(!validMnemonic(m)){setMessage("Enter a valid 24-word BIP-39 recovery phrase.");return}secretMnemonic=m;derive(m);go("vault")};
 const unlock=async()=>{try{const raw=localStorage.getItem("bunker-vault");if(!raw)throw new Error("No encrypted vault is stored on this device.");const m=await decryptMnemonic(JSON.parse(raw) as EncryptedVault,password.value);derive(m);secretMnemonic=m;go("home")}catch(e){setMessage(e instanceof Error?e.message:"Unlock failed.")}};
 const inspect=()=>{try{const e=parseEnvelope(offlineInput.value);setMessage(`Envelope format and checksum accepted for ${e.chainId===31337?"Anvil":"Sepolia"} · nonce ${e.nonce} · ${e.value} wei · rotation ${e.nextIndex}. Calldata, signature, and chain state are not independently verified.`)}catch(e){setMessage(e instanceof Error?e.message:"Envelope rejected.")}};
 const sample=()=>{const e=sealEnvelope({version:1,kind:"bunker-transfer",chainId:31337,safe:"0x0000000000000000000000000000000000000001",safeVersion:"1.4.1",guard:"0x0000000000000000000000000000000000000002",guardVersion:1,manifestId:`0x${"11".repeat(32)}`,nonce:"0",to:"0x0000000000000000000000000000000000000003",value:parseEther("0.01").toString(),data:"0x",operation:1,safeTxGas:"100000",baseGas:"0",gasPrice:"0",gasToken:ZERO_ADDRESS,refundReceiver:ZERO_ADDRESS,currentOwner:"0x0000000000000000000000000000000000000004",nextOwner:"0x0000000000000000000000000000000000000005",nextIndex:1,merkleProof:Array(5).fill(`0x${"22".repeat(32)}`) as `0x${string}`[],safeTxHash:`0x${"33".repeat(32)}`});download("bunker-unsigned-alpha.json",serializeEnvelope(e));setMessage("Unsigned local demonstration envelope downloaded. It is not a deployable Safe transaction.")};
 const toggle=()=>{const t=theme()==="dark"?"light":"dark";setTheme(t);localStorage.setItem("bunker-theme",t)};
 return <div class={`app ${theme()}`}><header><button class="wordmark" onClick={()=>go(connected()?"home":"welcome")}><span>B</span>Bunker</button><div class="alpha">Local / testnet alpha</div><button class="theme" onClick={toggle} aria-label="Toggle theme">{theme()==="dark"?"Light":"Dark"}</button></header><div class="warning"><b>Unaudited.</b> Never use mainnet or meaningful funds. Browser code cannot resist a compromised origin or extension.</div><div classList={{layout:true,"onboarding-layout":!connected()}}><Show when={connected()}><nav aria-label="Wallet sections"><button classList={{active:view()==="home"}} aria-current={view()==="home"?"page":undefined} onClick={()=>go("home")}><Icon name="shield"/>Wallet</button><button classList={{active:view()==="send"}} aria-current={view()==="send"?"page":undefined} onClick={()=>go("send")}><Icon name="route"/>Send</button><button classList={{active:view()==="offline"}} aria-current={view()==="offline"?"page":undefined} onClick={()=>go("offline")}><Icon name="file"/>Offline</button><button classList={{active:view()==="settings"}} aria-current={view()==="settings"?"page":undefined} onClick={()=>go("settings")}><Icon name="gear"/>Security</button><button class="exit" onClick={exitWallet}>Lock / exit</button></nav></Show><main>
 <Show when={message()}><p class="notice" role="status">{message()}</p></Show>
 <Show when={view()==="welcome"}><section class="welcome"><h1>Open your wallet.</h1><p>Create a new recovery phrase or load one you already have. Wallet tools appear after the wallet is unlocked.</p><div class="welcome-actions"><button class="primary" onClick={create}>Create wallet</button><button onClick={loadWallet}>Load wallet</button></div><button class="burner-link" onClick={openFaucet}>Or try a temporary Sepolia wallet</button><small>Temporary wallets disappear when this tab closes. Never use meaningful funds.</small></section></Show>
 <Show when={view()==="burner"}><section class="flow burner"><Step n="Sepolia" title="Ephemeral burner ready"/><h1>Fund it, then explore.</h1><p class="lead">A fresh address was created only in this tab and copied for the Google Cloud faucet. It disappears on refresh. Never send mainnet or meaningful funds.</p><div class="identifier"><small>Sepolia burner address · {burnerCopy()}</small><code>{burnerAddress()}</code></div><div class="big-stat burner-balance"><strong>{burnerBalance()}</strong></div><div class="actions"><button class="primary" onClick={openFaucet}>Open Sepolia faucet</button><button onClick={refreshBurner}>Refresh balance</button></div><p class="fine">This burner is not a deployed Safe and cannot sign or send in this alpha. The faucet opens on Google Cloud and may require sign-in or verification.</p></section></Show>
 <Show when={view()==="create"}><section class="flow"><Step n="1" title="Record all 24 words"/><h1>Your recovery phrase</h1><p class="lead">Write these words on paper in order. Anyone who gets them can control every derived owner. This page cannot guarantee erasure from browser memory.</p><ol class="words" ref={phraseEl}/><label class="check"><input type="checkbox" checked={backupConfirmed()} onChange={e=>setBackupConfirmed(e.currentTarget.checked)}/> I recorded the phrase away from this browser.</label><button class="primary" disabled={!backupConfirmed()} onClick={()=>go("confirm")}>Verify recovery</button></section></Show>
 <Show when={view()==="confirm"}><section class="flow"><Step n="2" title={secretMnemonic?"Confirm your backup":"Restore from words"}/><Show when={secretMnemonic} fallback={<><h1>Restore locally</h1><p class="lead">The phrase stays in memory for this session unless you explicitly create an encrypted vault.</p><textarea ref={restore} rows="5" spellcheck={false} autocomplete="off" placeholder="Enter 24 words"/><button class="primary" onClick={restorePhrase}>Validate recovery phrase</button></>}><h1>Prove the backup is complete</h1><p class="lead">Enter words 3, 9, and 18. No wallet is created until they match.</p><div class="confirm"><For each={[3,9,18]}>{(n,i)=><label>Word {n}<input ref={el=>confirmInputs[i()]=el} autocomplete="off" spellcheck={false}/></label>}</For></div><button class="primary" onClick={confirmBackup}>Continue to storage</button></Show></section></Show>
 <Show when={view()==="vault"}><section class="flow"><Step n="3" title="Choose local storage"/><h1>Protect this browser session</h1><div class="choice"><div><h2>Encrypted local vault <span>Recommended</span></h2><p>Argon2id derives a key; AES-256-GCM authenticates encrypted recovery data. A hostile page can still steal it while unlocked.</p><label>Password · 12 characters minimum<input ref={password} type="password" minlength="12" autocomplete="new-password"/></label><button class="primary" onClick={()=>finishVault(true)}>Encrypt and continue</button></div><div><h2>Seed phrase only</h2><p>Nothing is persisted. You must re-enter the phrase after reload. Browser memory cannot be reliably zeroized.</p><button onClick={()=>finishVault(false)}>Continue without saving</button></div></div></section></Show>
 <Show when={view()==="home"}><section class="dashboard"><Step n="Ready" title="Local owner state"/><h1>{owner()?"Owner prepared":"Vault locked"}</h1><Show when={owner()} fallback={<div class="unlock"><p>Unlock the encrypted vault to derive the current local owner.</p><label>Password<input ref={password} type="password" autocomplete="current-password"/></label><button class="primary" onClick={unlock}>Unlock locally</button></div>}><div class="identifier"><small>Current owner · derivation 0</small><code>{owner()}</code></div><div class="big-stat"><strong>{remaining()}</strong><span>ordinary rotations available</span></div><div class="state"><span>Safe deployment</span><b>Not configured</b><span>Network</span><b>Local Anvil only</b><span>Commitment</span><b>Pending deployment</b></div><button class="primary" disabled>Deploy guarded Safe — unavailable pending integration verification</button></Show></section></Show>
 <Show when={view()==="send"}><section class="flow"><Step n="Blocked" title="No guarded Safe configured"/><h1>Transfer path is locked</h1><p class="lead">The browser cannot sign or broadcast until a real Safe 1.4.1 deployment, immutable guard, code hashes, empty module list, and atomic bootstrap are independently verified.</p><div class="blocked-list"><p>ETH transfer only</p><p>Exactly one next-owner swap</p><p>Zero refund economics</p><p>Mainnet rejected at runtime</p></div><button class="primary" disabled>Review guarded transfer</button></section></Show>
 <Show when={view()==="offline"}><section class="flow"><Step n="File" title="Offline-capable envelope lab"/><h1>Inspect file structure</h1><p class="lead">This lab checks bounded JSON structure and its checksum only. It does not validate calldata, signatures, Safe hashes, or chain state.</p><textarea ref={offlineInput} rows="10" spellcheck={false} placeholder="Paste a Bunker envelope JSON"/><div class="actions"><button class="primary" onClick={inspect}>Validate envelope</button><button onClick={sample}>Download local example</button></div></section></Show>
 <Show when={view()==="settings"}><section class="flow"><Step n="Policy" title="Hard security gates"/><h1>What this alpha refuses</h1><div class="gates"><Gate title="Ethereum mainnet" status="Disabled" body="Requires an independent contract audit and restricted-value exercise."/><Gate title="Ledger and Trezor" status="Unverified" body="SDK integration is not a substitute for physical device and firmware testing."/><Gate title="Dynamic commitment refill" status="Disabled" body="A Merkle proof cannot prove derivation correctness. The authorization protocol is unresolved."/><Gate title="Manual and QR signing" status="Deferred" body="Proof-of-control and bounded QR parsing require separate review."/></div><button onClick={()=>{if(globalThis.confirm("Remove the encrypted vault from this device? You can restore access only with the recovery phrase.")){localStorage.removeItem("bunker-vault");wipe();setOwner();go("welcome")}}}>Remove local encrypted vault</button></section></Show>
 </main></div><footer><span>Bunker Wallet alpha</span><span>Safe 1.4.1 policy target · No analytics · No third-party scripts</span></footer></div>
}
const Step=(p:{n:string,title:string})=><div class="step"><span>{p.n}</span><b>{p.title}</b></div>;
const Gate=(p:{title:string,status:string,body:string})=><article class="gate"><div><h2>{p.title}</h2><span>{p.status}</span></div><p>{p.body}</p></article>;
