import { createSignal, For, onCleanup, Show } from "solid-js";
import { formatEther, isAddress, parseEther, parseUnits, type Address } from "viem";
import { decryptMnemonic, encryptMnemonic, newMnemonic, validMnemonic, type EncryptedVault } from "@bunker/vault";
import { clearEphemeralBurner, createEphemeralBurner, demoPostMessage, demoSendERC20, demoSendETH, deployDemoWallet, loadMnemonicSigner, readDemoWallet, readArbitrumSepoliaBalance, ARBITRUM_SEPOLIA_FAUCET } from "./burner";

type View="landing"|"setup"|"wallet"|"advanced"|"phrase"|"confirm"|"vault"|"load";
type Activity={label:string;hash?:string;index:number};
let secretMnemonic:string|undefined;
const short=(value:string)=>`${value.slice(0,8)}…${value.slice(-6)}`;
const wipe=()=>{secretMnemonic=undefined};
const Icon=(p:{name:"send"|"token"|"message"|"key"})=><svg viewBox="0 0 24 24" aria-hidden="true"><path d={p.name==="send"?"M3 11.2 20 3l-8.2 17-1.7-7-7.1-1.8Zm4.8-.8 3.5.9.9 3.5 3.9-8.1-8.3 3.7Z":p.name==="token"?"M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm1 5v1.1c1.7.3 2.7 1.3 2.8 2.8h-2c-.1-.8-.7-1.2-1.8-1.2-1 0-1.6.4-1.6 1 0 .5.4.8 1.3 1l1.3.3c2 .5 2.9 1.4 2.9 3 0 1.7-1.1 2.8-2.9 3.1V19h-2v-.9c-1.9-.3-3-1.4-3.1-3h2c.1.9.8 1.4 2 1.4 1.1 0 1.8-.5 1.8-1.2 0-.5-.4-.9-1.4-1.1l-1.4-.3c-1.8-.4-2.7-1.4-2.7-2.9 0-1.6 1.1-2.7 2.8-2.9V7h2Z":p.name==="message"?"M3 3h18v14H8l-5 4V3Zm2 2v12l2.3-2H19V5H5Zm3 3h8v2H8V8Zm0 4h6v2H8v-2Z":"M7 14a5 5 0 1 1 4.7-6.7L22 7v4h-3v3h-3v3h-4.3A5 5 0 0 1 7 14Zm0-2a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"}/></svg>;
export default function App(){
 const [view,setView]=createSignal<View>("landing"),[theme,setTheme]=createSignal<"light"|"dark">("light"),[setupAddress,setSetupAddress]=createSignal<Address>(),[setupBalance,setSetupBalance]=createSignal(0n),[walletAddress,setWalletAddress]=createSignal<Address>(),[walletBalance,setWalletBalance]=createSignal(0n),[owner,setOwner]=createSignal<Address>(),[rotation,setRotation]=createSignal(0),[busy,setBusy]=createSignal(""),[notice,setNotice]=createSignal(""),[activity,setActivity]=createSignal<Activity[]>([]),[action,setAction]=createSignal<"eth"|"token"|"message">("eth"),[confirmed,setConfirmed]=createSignal(false),[recoverable,setRecoverable]=createSignal(false);
 let phraseList!:HTMLOListElement,restore!:HTMLTextAreaElement,password!:HTMLInputElement,to!:HTMLInputElement,amount!:HTMLInputElement,token!:HTMLInputElement,decimals!:HTMLInputElement,message!:HTMLTextAreaElement,walletInput!:HTMLInputElement;let confirmInputs:HTMLInputElement[]=[];
 const go=(next:View)=>{setNotice("");setView(next)};
 const copy=(value?:string)=>{if(value&&navigator.clipboard)void navigator.clipboard.writeText(value).then(()=>setNotice("Address copied.")).catch(()=>setNotice("Select the address to copy it."))};
 const begin=()=>{const address=createEphemeralBurner();setRecoverable(false);setSetupAddress(address);setSetupBalance(0n);go("setup")};
 const openFaucet=()=>{const address=setupAddress();if(!address)return;copy(address);window.open(ARBITRUM_SEPOLIA_FAUCET,"_blank","noopener,noreferrer")};
 const checkFunding=async()=>{const address=setupAddress();if(!address)return;setBusy("Checking testnet balance…");try{const balance=await readArbitrumSepoliaBalance(address);setSetupBalance(balance);setNotice(balance>=parseEther("0.007")?"Funds received. Your stable wallet is ready to create.":"No test ETH yet. Faucets can take a minute.")}catch(e){setNotice(e instanceof Error?e.message:"Could not read Arbitrum Sepolia.")}finally{setBusy("")}};
 const refreshWallet=async()=>{const wallet=walletAddress();if(!wallet)return;const state=await readDemoWallet(wallet);setWalletBalance(state.balance);setOwner(state.owner);setRotation(state.index)};
 const createStableWallet=async()=>{setBusy("Creating your stable testnet address…");try{const address=await deployDemoWallet();setWalletAddress(address);localStorage.setItem("bunker-demo-wallet",address);await refreshWallet();setActivity([{label:"Stable wallet created",index:0}]);go("wallet")}catch(e){setNotice(e instanceof Error?e.message:"Wallet creation failed.")}finally{setBusy("")}};
 const afterAction=async(label:string,hash:string)=>{await refreshWallet();setActivity(rows=>[{label,hash,index:rotation()},...rows]);setNotice("Confirmed on Arbitrum Sepolia. A fresh owner key is now active.")};
 const runETH=async()=>{if(!walletAddress()||!isAddress(to.value)||!amount.value)return setNotice("Enter a valid recipient and ETH amount.");setBusy("Sending ETH and rotating the owner key…");try{await afterAction("ETH sent",await demoSendETH(walletAddress()!,to.value as Address,parseEther(amount.value)))}catch(e){setNotice(e instanceof Error?e.message:"Transfer failed.")}finally{setBusy("")}};
 const runToken=async()=>{if(!walletAddress()||!isAddress(token.value)||!isAddress(to.value))return setNotice("Enter valid token and recipient addresses.");setBusy("Sending token and rotating the owner key…");try{await afterAction("ERC-20 sent",await demoSendERC20(walletAddress()!,token.value as Address,to.value as Address,parseUnits(amount.value,Number(decimals.value||18))))}catch(e){setNotice(e instanceof Error?e.message:"Token transfer failed.")}finally{setBusy("")}};
 const runMessage=async()=>{if(!walletAddress()||!message.value.trim())return setNotice("Write a short message first.");setBusy("Posting your message and rotating the owner key…");try{await afterAction(`Posted “${message.value.trim()}”`,await demoPostMessage(walletAddress()!,message.value.trim()))}catch(e){setNotice(e instanceof Error?e.message:"Message failed.")}finally{setBusy("")}};
 const createPhrase=()=>{setConfirmed(false);secretMnemonic=newMnemonic();queueMicrotask(()=>{phraseList.replaceChildren(...secretMnemonic!.split(" ").map((word,index)=>{const li=document.createElement("li"),n=document.createElement("span");n.textContent=String(index+1);li.append(n,word);return li}))});go("phrase")};
 const verifyWords=()=>{const words=secretMnemonic?.split(" ");if(!words)return;if(confirmInputs.map(input=>input.value.trim().toLowerCase()).join("|")!==[2,8,17].map(i=>words[i]).join("|"))return setNotice("Those words do not match.");go("vault")};
 const finishSecure=async(persist:boolean)=>{if(!secretMnemonic)return;if(persist){if(password.value.length<12)return setNotice("Use at least 12 characters.");const encrypted=await encryptMnemonic(secretMnemonic,password.value,{chainId:421614,derivation:"m/44'/60'/7331'/0/index",sequenceVersion:1});localStorage.setItem("bunker-vault",JSON.stringify(encrypted))}const address=loadMnemonicSigner(secretMnemonic);setRecoverable(true);setSetupAddress(address);wipe();go("setup")};
 const load=async()=>{try{const entered=restore.value.trim();let mnemonic:string;if(entered){if(!validMnemonic(entered))throw new Error("Enter a valid 24-word recovery phrase.");mnemonic=entered}else if(localStorage.getItem("bunker-vault")){mnemonic=await decryptMnemonic(JSON.parse(localStorage.getItem("bunker-vault")!) as EncryptedVault,password.value)}else throw new Error("Enter a recovery phrase or load an encrypted vault.");setRecoverable(true);const supplied=walletInput.value.trim(),saved=(supplied||localStorage.getItem("bunker-demo-wallet")) as Address|null;if(saved&&isAddress(saved)){const state=await readDemoWallet(saved),recovered=loadMnemonicSigner(mnemonic,state.index);if(recovered.toLowerCase()!==state.owner.toLowerCase())throw new Error("This recovery phrase does not control the saved wallet.");setWalletAddress(saved);setWalletBalance(state.balance);setOwner(state.owner);setRotation(state.index);setActivity([{label:"Recovered stable wallet",index:state.index}]);go("wallet")}else{setSetupAddress(loadMnemonicSigner(mnemonic));go("setup")} }catch(e){setNotice(e instanceof Error?e.message:"Wallet could not be loaded.")}};
 const exit=()=>{wipe();clearEphemeralBurner();setSetupAddress();setWalletAddress();setOwner();setActivity([]);go("landing")};
 onCleanup(()=>{wipe();clearEphemeralBurner()});
 return <div class={`site ${theme()}`}><header class="top"><button class="brand" onClick={()=>go(walletAddress()?"wallet":"landing")}><span>B</span>Bunker</button><nav><Show when={walletAddress()}><button onClick={()=>go("wallet")}>Wallet</button></Show><button onClick={()=>go("advanced")}>Setup options</button><button class="theme" onClick={()=>setTheme(theme()==="light"?"dark":"light")}>{theme()==="light"?"Dark":"Light"}</button><Show when={walletAddress()}><button onClick={exit}>Exit</button></Show></nav></header><Show when={notice()}><div class="toast" role="status">{notice()}</div></Show>
 <main>
 <Show when={view()==="landing"}><section class="hero-new"><div class="hero-copy"><span class="status-dot">Arbitrum Sepolia demo</span><h1>One address.<br/>Fresh keys.</h1><p>Keep one familiar Ethereum address while Bunker rotates the signing owner after every action—reducing exposure to future quantum attacks.</p><div class="hero-actions"><button class="primary" onClick={begin}>Create a Bunker</button><a class="button-link" href="#how-it-works">How it works</a></div><small>Unaudited testnet software. Never use mainnet or meaningful funds.</small></div><div class="mechanism" aria-label="Stable wallet address with rotating owner keys"><div class="address-head"><span>YOUR WALLET ADDRESS</span><b>Stays the same</b></div><code>0x71A4…92F0</code><div class="key-track"><div class="key spent"><Icon name="key"/><span>Key 08</span><small>Used</small></div><i>→</i><div class="key active"><Icon name="key"/><span>Key 09</span><small>Active</small></div><i>→</i><div class="key next"><Icon name="key"/><span>Key 10</span><small>Next</small></div></div><div class="action-line"><span>Send · Token · Message</span><b>Owner advances</b></div></div></section><div class="trust-line"><span>Ethereum L2</span><span>Standard ECDSA</span><span>MIT open source</span><span>Safe architecture planned</span></div><section class="why" id="how-it-works"><div class="why-head"><span>Why Bunker?</span><h2>Rotate the keys.<br/>Keep the wallet.</h2></div><div class="why-list"><article><b>01</b><div><h3>One address</h3><p>Receive assets and build history without changing your wallet identity.</p></div></article><article><b>02</b><div><h3>Atomic rotation</h3><p>A supported action and the move to its next owner succeed together.</p></div></article><article><b>03</b><div><h3>Your keys, your control</h3><p>Quick keys stay in memory. Recovery setup stays local and can be encrypted.</p></div></article><article><b>04</b><div><h3>Familiar Ethereum</h3><p>Standard ECDSA and open-source contracts. No new chain or experimental cryptography.</p></div></article></div></section><section class="flow"><span>How it works</span><h2>One wallet. Fresh keys.<br/>Every action.</h2><ol><li><b>Create</b><small>Make a browser key.</small></li><li><b>Fund</b><small>Add Arbitrum Sepolia ETH.</small></li><li><b>Deploy</b><small>Get one wallet address.</small></li><li><b>Use</b><small>Act and rotate atomically.</small></li></ol></section><section class="roadmap"><div><span>The important distinction</span><h2>Less exposure.<br/>Not quantum-proof.</h2></div><p>Bunker still uses standard ECDSA. Rotation reduces how long an exposed owner remains useful; it does not make Ethereum post-quantum secure.</p><div class="roadmap-links"><button class="primary" onClick={begin}>Get started</button><a href="https://github.com/SilentCicero/bunker-wallet" target="_blank" rel="noreferrer">View the source →</a></div><small>Safe, Ledger, Trezor, and offline signing remain planned and audit-gated.</small></section></Show>
 <Show when={view()==="setup"}><section class="setup"><div class="stepper"><span class="done">1 <b>Key</b></span><span classList={{done:setupBalance()>=parseEther("0.007")}}>2 <b>Fund</b></span><span classList={{done:Boolean(walletAddress())}}>3 <b>Create</b></span></div><h1>{setupBalance()>=parseEther("0.007")?"Create your stable wallet.":"Add Arbitrum Sepolia test ETH."}</h1><p>{setupBalance()>=parseEther("0.007")?"Your setup key is funded. Create the wallet contract and move the test ETH into its permanent address.":"Your temporary setup address is ready and copied when you open the faucet."}</p><Show when={!recoverable()}><p class="ephemeral-note">Quick setup is memory-only. Do not refresh during funding or after wallet creation. Use Recovery phrase setup if you want restoration later.</p></Show><div class="setup-address"><span>Setup address</span><code>{setupAddress()}</code><button onClick={()=>copy(setupAddress())}>Copy</button></div><div class="balance-row"><span>Setup balance</span><strong>{Number(formatEther(setupBalance())).toFixed(4)} ETH</strong></div><Show when={setupBalance()>=parseEther("0.007")} fallback={<div class="setup-actions"><button class="primary" onClick={openFaucet}>Open Arbitrum faucet</button><button onClick={checkFunding} disabled={Boolean(busy())}>{busy()||"I funded it — check balance"}</button></div>}><button class="primary wide" onClick={createStableWallet} disabled={Boolean(busy())}>{busy()||"Create stable wallet"}</button></Show><button class="text-button" onClick={()=>go("advanced")}>Use another setup method</button></section></Show>
 <Show when={view()==="wallet"&&walletAddress()}><section class="wallet"><div class="wallet-top"><div><span class="status-dot">Arbitrum Sepolia · live</span><h1>{Number(formatEther(walletBalance())).toFixed(4)} ETH</h1><small class="spendable">Keep 0.001 ETH for the next owner key on every action.</small><button class="address-copy" onClick={()=>copy(walletAddress())}>{short(walletAddress()!)} · Copy</button></div><div class="rotation-card"><span>OWNER ROTATION</span><strong>Key {rotation()+1}</strong><p>Active underneath your stable address</p><div><i style={{width:`${Math.min(100,(rotation()+1)*8)}%`}}/></div></div></div><div class="stable"><span>Stable wallet address</span><code>{walletAddress()}</code><b>Does not change</b></div><div class="wallet-grid"><section class="actions-panel"><div class="action-tabs"><button classList={{active:action()==="eth"}} onClick={()=>setAction("eth")}><Icon name="send"/>ETH</button><button classList={{active:action()==="token"}} onClick={()=>setAction("token")}><Icon name="token"/>Token</button><button classList={{active:action()==="message"}} onClick={()=>setAction("message")}><Icon name="message"/>Wall</button></div><Show when={action()==="eth"}><h2>Send ETH</h2><label>Recipient<input ref={to} placeholder="0x…"/></label><label>Amount<input ref={amount} inputmode="decimal" placeholder="0.001"/></label><button class="primary wide" onClick={runETH} disabled={Boolean(busy())}>{busy()||"Send + rotate key"}</button></Show><Show when={action()==="token"}><h2>Send ERC-20</h2><label>Token contract<input ref={token} placeholder="0x…"/></label><label>Recipient<input ref={to} placeholder="0x…"/></label><div class="split"><label>Amount<input ref={amount} placeholder="10"/></label><label>Decimals<input ref={decimals} value="18"/></label></div><button class="primary wide" onClick={runToken} disabled={Boolean(busy())}>{busy()||"Send token + rotate"}</button></Show><Show when={action()==="message"}><h2>Post to the Bunker wall</h2><p class="muted">Write a short on-chain message from this stable address.</p><textarea ref={message} maxlength="140" placeholder="Hello from my rotating wallet"/><button class="primary wide" onClick={runMessage} disabled={Boolean(busy())}>{busy()||"Post + rotate key"}</button></Show></section><aside class="activity"><h2>Under the hood</h2><For each={activity()}>{item=><div class="activity-row"><span>{item.index===rotation()?"Current":"Done"}</span><p><b>{item.label}</b><small>Owner key {item.index+1}</small></p>{item.hash&&<a href={`https://sepolia.arbiscan.io/tx/${item.hash}`} target="_blank" rel="noreferrer">View</a>}</div>}</For></aside></div></section></Show>
 <Show when={view()==="advanced"}><section class="advanced"><button class="back" onClick={()=>go("landing")}>← Back</button><h1>Choose how to protect the setup key.</h1><p>Each method creates a stable wallet address with automatic owner rotation.</p><div class="option-list"><button onClick={createPhrase}><span>Recovery phrase</span><small>24 words · optional check and password</small><b>Set up</b></button><button onClick={()=>go("load")}><span>Load existing wallet</span><small>Encrypted vault or 24 words</small><b>Load</b></button><button disabled><span>Ledger</span><small>Hardware setup · compatibility verification in progress</small><b>Soon</b></button><button disabled><span>Trezor</span><small>Hardware setup · compatibility verification in progress</small><b>Soon</b></button><button disabled><span>EVM wallet</span><small>Manual next-key proof required</small><b>Soon</b></button></div></section></Show>
 <Show when={view()==="phrase"}><section class="secure"><span class="status-dot">Secure setup</span><h1>Write down these 24 words.</h1><p>Keep them offline. They recover every owner key in sequence.</p><ol class="words" ref={phraseList}/><label class="check"><input type="checkbox" checked={confirmed()} onChange={e=>setConfirmed(e.currentTarget.checked)}/> I saved the phrase offline.</label><div class="secure-actions"><button class="primary" disabled={!confirmed()} onClick={()=>go("confirm")}>Check my backup</button><button disabled={!confirmed()} onClick={()=>go("vault")}>Skip check</button></div></section></Show>
 <Show when={view()==="confirm"}><section class="secure"><h1>Quick recovery check.</h1><p>Enter words 3, 9, and 18.</p><div class="confirm"><For each={[3,9,18]}>{(n,i)=><label>Word {n}<input ref={el=>confirmInputs[i()]=el}/></label>}</For></div><button class="primary" onClick={verifyWords}>Continue</button></section></Show>
 <Show when={view()==="vault"}><section class="secure"><h1>Add a password?</h1><p>Optional. A password encrypts the recovery phrase on this device.</p><label>Password · 12 characters minimum<input ref={password} type="password" autocomplete="new-password"/></label><div class="secure-actions"><button class="primary" onClick={()=>finishSecure(true)}>Encrypt and continue</button><button onClick={()=>finishSecure(false)}>Continue without saving</button></div></section></Show>
 <Show when={view()==="load"}><section class="secure"><button class="back" onClick={()=>go("advanced")}>← Back</button><h1>Load wallet.</h1><Show when={localStorage.getItem("bunker-vault")}><label>Vault password<input ref={password} type="password" autocomplete="current-password"/></label></Show><label>Recovery phrase {localStorage.getItem("bunker-vault")?"(or leave blank to use this device’s vault)":""}<textarea ref={restore} rows="4" autocomplete="off" spellcheck={false}/></label><label>Stable wallet address · optional<input ref={walletInput} placeholder="0x… (needed on a new device)"/></label><button class="primary" onClick={load}>Load wallet</button></section></Show>
 </main><footer><span>Bunker · Arbitrum Sepolia demo</span><span>Stable address · Rotating ECDSA owners</span></footer></div>
}
