const DB_NAME="bunker-unlocked-session",STORE="keys",ACTIVE="active",LEGACY="bunker-unlocked-wallet";
type Envelope={id:string;nonce:string;ciphertext:string};
const hex=(bytes:Uint8Array)=>Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");
const bytes=(value:string)=>new Uint8Array(value.match(/.{2}/g)?.map(v=>parseInt(v,16))??[]);
const db=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const get=async<T>(id:string)=>{const database=await db();const value=await new Promise<T|undefined>((resolve,reject)=>{const request=database.transaction(STORE).objectStore(STORE).get(id);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});database.close();return value};
const put=async(id:string,value:unknown)=>{const database=await db();await new Promise<void>((resolve,reject)=>{const request=database.transaction(STORE,"readwrite").objectStore(STORE).put(value,id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});database.close()};
const remove=async(...ids:string[])=>{const database=await db();await new Promise<void>((resolve,reject)=>{const transaction=database.transaction(STORE,"readwrite"),store=transaction.objectStore(STORE);for(const id of ids)store.delete(id);transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)});database.close()};
export async function cacheUnlockedMnemonic(mnemonic:string){await clearUnlockedMnemonic();const id=crypto.randomUUID(),key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]),nonce=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(mnemonic);try{const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:nonce},key,plain));await put(id,key);await put(ACTIVE,{id,nonce:hex(nonce),ciphertext:hex(ciphertext)} satisfies Envelope)}finally{plain.fill(0)}}
const decrypt=async(envelope:Envelope)=>{const key=await get<CryptoKey>(envelope.id);if(!key)throw new Error();const plain=new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv:bytes(envelope.nonce)},key,bytes(envelope.ciphertext)));try{return new TextDecoder().decode(plain)}finally{plain.fill(0)}};
export async function restoreUnlockedMnemonic(){const envelope=await get<Envelope>(ACTIVE);if(envelope){try{return await decrypt(envelope)}catch{await clearUnlockedMnemonic();return}}const raw=sessionStorage.getItem(LEGACY);if(!raw)return;try{const legacy=JSON.parse(raw) as Envelope&{expiresAt?:number};if(legacy.expiresAt&&legacy.expiresAt<Date.now())throw new Error();const mnemonic=await decrypt(legacy);await remove(legacy.id);sessionStorage.removeItem(LEGACY);await cacheUnlockedMnemonic(mnemonic);return mnemonic}catch{try{const id=(JSON.parse(raw) as Envelope).id;if(id)await remove(id)}catch{}sessionStorage.removeItem(LEGACY);return}}
export async function clearUnlockedMnemonic(){const envelope=await get<Envelope>(ACTIVE);await remove(ACTIVE,...(envelope?.id?[envelope.id]:[]))}
