const DB_NAME="bunker-unlocked-session",STORE="keys",SESSION_KEY="bunker-unlocked-wallet",TTL=8*60*60*1000;
type SessionEnvelope={id:string;nonce:string;ciphertext:string;expiresAt:number};
const hex=(bytes:Uint8Array)=>Array.from(bytes,b=>b.toString(16).padStart(2,"0")).join("");
const bytes=(value:string)=>new Uint8Array(value.match(/.{2}/g)?.map(v=>parseInt(v,16))??[]);
const db=()=>new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const put=async(id:string,key:CryptoKey,expiresAt:number)=>{const database=await db();await new Promise<void>((resolve,reject)=>{const request=database.transaction(STORE,"readwrite").objectStore(STORE).put({key,expiresAt},id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});database.close()};
const get=async(id:string)=>{const database=await db();const key=await new Promise<CryptoKey|undefined>((resolve,reject)=>{const request=database.transaction(STORE).objectStore(STORE).get(id);request.onsuccess=()=>resolve(request.result?.expiresAt>Date.now()?request.result.key:undefined);request.onerror=()=>reject(request.error)});database.close();return key};
const remove=async(id:string)=>{const database=await db();await new Promise<void>((resolve,reject)=>{const request=database.transaction(STORE,"readwrite").objectStore(STORE).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});database.close()};
export async function cacheUnlockedMnemonic(mnemonic:string){await clearUnlockedMnemonic();const id=crypto.randomUUID(),key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]),nonce=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(mnemonic);try{const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:nonce},key,plain)),expiresAt=Date.now()+TTL;await put(id,key,expiresAt);sessionStorage.setItem(SESSION_KEY,JSON.stringify({id,nonce:hex(nonce),ciphertext:hex(ciphertext),expiresAt} satisfies SessionEnvelope))}finally{plain.fill(0)}}
export async function restoreUnlockedMnemonic(){const raw=sessionStorage.getItem(SESSION_KEY);if(!raw)return;try{const envelope=JSON.parse(raw) as SessionEnvelope;if(!envelope.id||envelope.expiresAt<Date.now())throw new Error();const key=await get(envelope.id);if(!key)throw new Error();const plain=new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv:bytes(envelope.nonce)},key,bytes(envelope.ciphertext)));try{return new TextDecoder().decode(plain)}finally{plain.fill(0)}}catch{await clearUnlockedMnemonic();return}}
export async function clearUnlockedMnemonic(){const raw=sessionStorage.getItem(SESSION_KEY);sessionStorage.removeItem(SESSION_KEY);if(!raw)return;try{const id=(JSON.parse(raw) as SessionEnvelope).id;if(id)await remove(id)}catch{}}
