import solc from "solc";
import { dirname, join, normalize } from "node:path";
import { keccak256, type Hex } from "viem";

const root = "packages/contracts";
const guardEntry = "src/BunkerRotationGuard.sol";
const setupEntry = "src/BunkerSafeSetup.sol";
const proxyEntry = "@safe-global/safe-contracts/contracts/proxies/SafeProxy.sol";
const sources: Record<string, { content: string }> = {};
const queue = [guardEntry, setupEntry, proxyEntry];
const diskPath = (name: string) => name.startsWith("@safe-global/safe-contracts/")
  ? join(root, "lib", name)
  : join(root, name);
while (queue.length) {
  const name = queue.pop()!;
  if (sources[name]) continue;
  const content = await Bun.file(diskPath(name)).text();
  sources[name] = { content };
  for (const match of content.matchAll(/import\s+(?:[^"']+from\s+)?["']([^"']+)["'];/g)) {
    const specifier = match[1]!;
    queue.push(specifier.startsWith(".") ? normalize(join(dirname(name), specifier)).replaceAll("\\", "/") : specifier);
  }
}
const output = JSON.parse(solc.compile(JSON.stringify({
  language: "Solidity",
  sources,
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object", "evm.deployedBytecode.object", "evm.deployedBytecode.immutableReferences"] } },
  },
}))) as {
  errors?: { severity: string; formattedMessage: string }[];
  contracts?: Record<string, Record<string, { abi: unknown[]; evm: { bytecode: { object: string }; deployedBytecode: { object: string; immutableReferences?: Record<string, { start: number; length: number }[]> } } }>>;
};
for (const error of output.errors ?? []) if (error.severity === "error") console.error(error.formattedMessage);
if ((output.errors ?? []).some(error => error.severity === "error")) process.exit(1);
const guard = output.contracts?.[guardEntry]?.BunkerRotationGuard;
const setup = output.contracts?.[setupEntry]?.BunkerSafeSetup;
const proxy = output.contracts?.[proxyEntry]?.SafeProxy;
if (!guard?.evm.bytecode.object || !setup?.evm.bytecode.object || !proxy?.evm.deployedBytecode.object) throw new Error("Contract bytecode was not produced.");
const patchedGuardRuntime = Buffer.from(guard.evm.deployedBytecode.object, "hex");
for (const refs of Object.values(guard.evm.deployedBytecode.immutableReferences ?? {})) {
  const value: Hex = refs.length === 3
    ? "0x0000000000000000000000009641d764fc13c8b624c04430c7356c1c7c8102e2"
    : refs.length === 2
      ? "0xecd5bd14a08c5d2122379900b2f272bdf107a7e92423c10dd5fe3254386c9939"
      : (() => { throw new Error("Unexpected guard immutable layout."); })();
  for (const ref of refs) Buffer.from(value.slice(2), "hex").copy(patchedGuardRuntime, ref.start, 0, ref.length);
}
const guardRuntimeHash = keccak256(`0x${patchedGuardRuntime.toString("hex")}`);
// Canonical SafeProxy runtime produced by the verified Safe 1.4.1 proxy factory.
const proxyRuntimeHash = "0xd7d408ebcd99b2b70be43e20253d6d92a8ea8fab29bd3be7f55b10032331fb4c";
await Bun.write("apps/web/src/safeArtifacts.ts", `// Generated by scripts/compile-contract.ts with ${solc.version()}\nexport const bunkerGuardAbi = ${JSON.stringify(guard.abi)} as const;\nexport const bunkerGuardBytecode = "0x${guard.evm.bytecode.object}" as const;\nexport const bunkerGuardRuntimeBytecode = "0x${patchedGuardRuntime.toString("hex")}" as const;\nexport const bunkerGuardRuntimeHash = "${guardRuntimeHash}" as const;\nexport const safeProxyRuntimeHash = "${proxyRuntimeHash}" as const;\nexport const bunkerSetupAbi = ${JSON.stringify(setup.abi)} as const;\nexport const bunkerSetupBytecode = "0x${setup.evm.bytecode.object}" as const;\nexport const bunkerSetupRuntimeBytecode = "0x${setup.evm.deployedBytecode.object}" as const;\n`);
console.log(`Compiled BunkerRotationGuard (${guard.evm.bytecode.object.length / 2} bytes), BunkerSafeSetup (${setup.evm.bytecode.object.length / 2} bytes) with solc ${solc.version()}.`);
