import solc from "solc";
import { dirname, join, normalize } from "node:path";

const root = "packages/contracts";
const entry = "src/BunkerRotationGuard.sol";
const demoEntry = "src/BunkerDemoWallet.sol";
const sources: Record<string, { content: string }> = {};
const queue = [entry, demoEntry];
const diskPath = (name: string) => name.startsWith("@safe-global/safe-contracts/")
  ? join(root, "lib", name)
  : join(root, name);
while (queue.length) {
  const name = queue.pop()!;
  if (sources[name]) continue;
  const content = await Bun.file(diskPath(name)).text();
  sources[name] = { content };
  for (const match of content.matchAll(/import\s+(?:[^"']+from\s+)?["']([^"']+)["'];/g)) {
    const specifier = match[1]!;
    queue.push(specifier.startsWith(".") ? normalize(join(dirname(name), specifier)).replaceAll("\\", "/") : specifier);
  }
}
const output = JSON.parse(solc.compile(JSON.stringify({
  language: "Solidity", sources,
  settings: { optimizer: { enabled: true, runs: 100000 }, viaIR: true, outputSelection: { [entry]: { BunkerRotationGuard: ["abi", "evm.bytecode.object"] }, [demoEntry]: { BunkerDemoWallet: ["abi", "evm.bytecode.object"] } } },
}))) as { errors?: { severity: string; formattedMessage: string }[]; contracts?: Record<string, Record<string, { abi: unknown[]; evm: { bytecode: { object: string } } }>> };
for (const error of output.errors ?? []) if (error.severity === "error") console.error(error.formattedMessage);
if ((output.errors ?? []).some(error => error.severity === "error")) process.exit(1);
const contract = output.contracts?.[entry]?.BunkerRotationGuard;
if (!contract?.evm.bytecode.object) throw new Error("BunkerRotationGuard bytecode was not produced.");
const demo = output.contracts?.[demoEntry]?.BunkerDemoWallet;
if (!demo?.evm.bytecode.object) throw new Error("BunkerDemoWallet bytecode was not produced.");
await Bun.write("apps/web/src/demoContract.ts", `// Generated by scripts/compile-contract.ts with ${solc.version()}\nexport const demoWalletAbi = ${JSON.stringify(demo.abi)} as const;\nexport const demoWalletBytecode = "0x${demo.evm.bytecode.object}" as const;\n`);
console.log(`Compiled BunkerRotationGuard (${contract.evm.bytecode.object.length / 2} bytes) and BunkerDemoWallet (${demo.evm.bytecode.object.length / 2} bytes) with solc ${solc.version()}.`);
