import { argon2idAsync } from "@noble/hashes/argon2.js";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils.js";
import { generateMnemonic, validateMnemonic } from "@scure/bip39";
import { wordlist } from "@scure/bip39/wordlists/english.js";
import { SecurityPolicyError } from "@bunker/core";
type KdfParams={memoryKiB:number;iterations:number;parallelism:1};
const KDF:KdfParams={memoryKiB:19456,iterations:2,parallelism:1};
export type VaultMetadata={chainId:31337|11155111;safe?:`0x${string}`;derivation:"m/44'/60'/7331'/0/index";sequenceVersion:1};
export type EncryptedVault={version:1;kdf:{name:"argon2id";memoryKiB:number;iterations:number;parallelism:number;salt:string};cipher:{name:"AES-256-GCM";nonce:string;ciphertext:string};metadata:VaultMetadata};
export function newMnemonic():string{return generateMnemonic(wordlist,256)}
export function validMnemonic(value:string):boolean{return value.trim().split(/\s+/).length===24&&validateMnemonic(value.trim(),wordlist)}
const aad=(metadata:VaultMetadata)=>new TextEncoder().encode(JSON.stringify({version:1,kdf:"argon2id",cipher:"AES-256-GCM",metadata}));
async function key(password:string,salt:Uint8Array,params:KdfParams=KDF){if(password.length<12||password.length>256)throw new SecurityPolicyError("Password must be 12–256 characters.");return argon2idAsync(new TextEncoder().encode(password),salt,{m:params.memoryKiB,t:params.iterations,p:params.parallelism,dkLen:32});}
export async function encryptMnemonic(mnemonic:string,password:string,metadata:VaultMetadata):Promise<EncryptedVault>{if(!validMnemonic(mnemonic))throw new SecurityPolicyError("Recovery phrase is invalid.");const salt=crypto.getRandomValues(new Uint8Array(16)),nonce=crypto.getRandomValues(new Uint8Array(12)),derived=await key(password,salt),plain=new TextEncoder().encode(mnemonic);try{const k=await crypto.subtle.importKey("raw",Uint8Array.from(derived).buffer,"AES-GCM",false,["encrypt"]),cipher=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv:Uint8Array.from(nonce).buffer,additionalData:Uint8Array.from(aad(metadata)).buffer},k,Uint8Array.from(plain).buffer));return{version:1,kdf:{name:"argon2id",...KDF,salt:bytesToHex(salt)},cipher:{name:"AES-256-GCM",nonce:bytesToHex(nonce),ciphertext:bytesToHex(cipher)},metadata}}finally{derived.fill(0);plain.fill(0)}}
function validate(v:EncryptedVault){if(v.version!==1||v.kdf?.name!=="argon2id"||v.cipher?.name!=="AES-256-GCM")throw new SecurityPolicyError("Vault format is unsupported.");if(v.kdf.memoryKiB<16384||v.kdf.memoryKiB>131072||v.kdf.iterations<2||v.kdf.iterations>8||v.kdf.parallelism!==1)throw new SecurityPolicyError("Vault KDF parameters are unsafe.");if(!/^[0-9a-f]{32}$/.test(v.kdf.salt)||!/^[0-9a-f]{24}$/.test(v.cipher.nonce)||!/^([0-9a-f]{2})+$/.test(v.cipher.ciphertext)||v.cipher.ciphertext.length>4096)throw new SecurityPolicyError("Vault encoding is invalid.");}
export async function decryptMnemonic(vault:EncryptedVault,password:string):Promise<string>{validate(vault);const salt=hexToBytes(vault.kdf.salt),nonce=hexToBytes(vault.cipher.nonce),derived=await key(password,salt,{memoryKiB:vault.kdf.memoryKiB,iterations:vault.kdf.iterations,parallelism:1});try{const k=await crypto.subtle.importKey("raw",Uint8Array.from(derived).buffer,"AES-GCM",false,["decrypt"]),plain=new Uint8Array(await crypto.subtle.decrypt({name:"AES-GCM",iv:Uint8Array.from(nonce).buffer,additionalData:Uint8Array.from(aad(vault.metadata)).buffer},k,Uint8Array.from(hexToBytes(vault.cipher.ciphertext)).buffer)),mnemonic=new TextDecoder().decode(plain);plain.fill(0);if(!validMnemonic(mnemonic))throw new Error();return mnemonic}catch{throw new SecurityPolicyError("Vault could not be opened. The password or file is invalid.")}finally{derived.fill(0)}}
